### ISSUE TITLE
Keshav - completed

### ISSUE THREAD

**Issue by Keshav-Murali** [sbenstewart/GitHubEvent#12]
https://github.com/Keshav-Murali/One-small-step

**Comment by sbenstewart** [comment]
Well done.
You have successfully completed the tasks. Hope you learnt something new and useful.
<b>Have a great day :)</b>

**Comment by sbenstewart** [comment]
Got a sticker for you for the completion of the task.
Good job. Keep it up.
You can get them from Ben +91 9489408090.
**Have a great day :)**
