### ISSUE TITLE
S Nithish Kumar -completed

### ISSUE THREAD

**Issue by NithishKumar0201** [sbenstewart/GitHubEvent#13]
https://github.com/NithishKumar0201/One-small-step.git

**Comment by sbenstewart** [comment]
Well done.
You have successfully completed the tasks. Hope you learnt something new and useful.
You have used a different project directory structure from what was specified. Can you explain why you opted for this one ?
<b>Have a great day :)</b>

**Comment by sbenstewart** [comment]
I'll close this as of now.

**Comment by sbenstewart** [comment]
Great you had done this. 
You can collect your stickers from me.
**Have a great day :)**
